name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Load project git submodules
      run: git submodule update --init --recursive
    - name: Build with Gradle
      run: cd matrix-malos-demo && ./cibuild.sh
